### ISSUE TITLE
Blog / Website link not working

### ISSUE THREAD

**Issue by DylanDelobel** [MarkoCen/github-flair#1]
I generated my own Github Flair and website link didn't work

The link redirect me to this `https://markocen.github.io/github-flair/dylandelobel.com`

I suggest to add `http://` before to make it work

**Comment by MarkoCen** [comment]
Oops... Thanks for reporting this issue. I would fix it ASAP

**Comment by MarkoCen** [comment]
fixed f7604023652db1d86b007f337f90093bf3eba244
