### ISSUE TITLE
403 Forbidden

### ISSUE THREAD

**Issue by d6o** [MarkoCen/github-flair#3]
When i click on Generate button nothing happen. Looking at the console, i found out that the request returned 403 status code.

![image](https://cloud.githubusercontent.com/assets/683170/24593482/4497e908-17fa-11e7-806a-3a561a0144af.png)

**Comment by MarkoCen** [comment]
Seem like the website reached the GitHub API rate limit

> For unauthenticated requests, the rate limit allows you to make up to 60 requests per hour

You could fork this repo and host it on your IP to eliminate the limit.
